name: Python CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    container:
      image: ryukzak/python-tools

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: poetry install

      - name: Run tests with coverage
        run: |
          coverage run -m pytest --verbose
          find . -type f -name "*.py" | xargs -t coverage report

      - name: Check code formatting
        run: ruff format --check .
